version: "3.6"
services:
  inference-engine:
    image: capx-object
    container_name: inference-engine
    environment:
    - ROOT_LOGLEVEL=WARNING # logging level can be "DEBUG", "INFO", "WARNING"
    - BASEWORKER_LOGLEVEL=WARNING # logging level can be "DEBUG", "INFO", "WARNING"
    - HANDLER_LOGLEVEL=INFO # logging level can be "DEBUG", "INFO", "WARNING"
    - SERVER_BIND_INTERFACE=0.0.0.0 # default to accept from all IP
    - SERVER_PORT=80 # default to accept requests on port 80
    - SERVER_ENDPOINT=receive # default URL endpoint to receive request - CAPX_OBJECT_FILTER=person,bicycle,car
    - CAPX_WORKER_NAME=object # do not change, leave as it is
    - CAPX_FORCE_CPU=true # or false
    ports:
      - "8081:80"
    volumes:
      - ./__logs:/workspace/logs
      - ./__images:/workspace/images
    restart: unless-stopped
    networks:
    - default

networks:
  default:
    name: app-net